site_name: Документация
site_url: https://lilyerma.github.io

theme:
    language: ru
    features:
    - navigation.tabs
    name: material
    logo: assets/Frame_21533.svg
        # Palette toggle for light mode
    palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference


markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true 

plugins:
  - search
#  - i18n:
#          default_language: ru
#          languages: 
#          en: English
#          ru: Русский

nav:
  - Home: index.md
  - Быстрый старт: quick-start.md
  - О системе: 
    - Введение: about.md
    - Основные понятия: reference.md
  - Гайды:
    - Подключение облаков: manage-connection.md
    - Создание подписки: create-subscription.md
    - Перемещение ВМ: vm-transfers.md
    - Работа с ВМ: vm-management.md
    - Отчеты: usage-reports.md
 # - How-Tos: 
     

